[versions]
agp = "8.13.2"
kotlin = "2.3.0"

app-version = "1.4"
android-compileSdk = "36"
android-minSdk = "31"
android-targetSdk = "36"

coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
material-icons = "1.7.8"
koin = "4.1.1"
palette = "1.0.0"
browser = "1.9.0"
datastore = "1.2.0"
preference = "2.1.0"
colorpicker = "1.1.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "material-icons" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons" }
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
zhanghai-preference = { group = "me.zhanghai.compose.preference", name = "preference", version.ref = "preference" }
skydoves-colorpicker = { group = "com.github.skydoves", name = "colorpicker-compose", version.ref = "colorpicker" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

